
INSERT INTO skills VALUES (1,'Farming');
INSERT INTO skills VALUES (2,'Mining');
INSERT INTO skills VALUES (3,'Foraging');
INSERT INTO skills VALUES (4,'Fishing');
INSERT INTO skills VALUES (5,'Combat');

INSERT INTO professions VALUES (1,'Rancher',5,'Animal products worth 20% more.',1,null);
INSERT INTO professions VALUES (2,'Tiller',5,'Crops worth 10% more.(Bonus applies to all Vegetables and Flowers, plus any Fruit that has not been foraged) ',1,null);
INSERT INTO professions VALUES (3,'Coopmaster',10,'Befriend coop animals quicker. Incubation time (for Incubator and Ostrich Incubator) cut in half. ',1,1);
INSERT INTO professions VALUES (4,'Shepherd',10,'Befriend barn animals quicker. Sheep produce wool faster.',1,1);
INSERT INTO professions VALUES (5,'Artisan',10,'Artisan goods (wine, cheese, oil, etc.) worth 40% more. ',1,2);
INSERT INTO professions VALUES (6,'Agriculturist',10,'All crops grow 10% faster. ',1,2);
INSERT INTO professions VALUES (7,'Miner',5,' +1 ore per vein.',2,null);
INSERT INTO professions VALUES (8,'Geologist',5,'Chance for gems to appear in pairs.',2,null);
INSERT INTO professions VALUES (9,'Blacksmith',10,'Metal bars worth 50% more.',2,7);
INSERT INTO professions VALUES (10,'Excavator',10,'Chance to find geodes doubled.',2,7);
INSERT INTO professions VALUES (11,'Prospector',10,'Chance to find coal doubled.',2,8);
INSERT INTO professions VALUES (12,'Gemologist',10,'Gems worth 30% more.',2,8);
INSERT INTO professions VALUES (13,'Forester',5,'Gain 25% more wood when chopping',3,null);
INSERT INTO professions VALUES (14,'Gatherer',5,'Chance for double harvest of foraged items.',3,null);
INSERT INTO professions VALUES (15,'Lumberjack',10,'All trees have a chance to drop hardwood.',3,13);
INSERT INTO professions VALUES (16,'Tapper',10,'Syrups worth 25% more.',3,13);
INSERT INTO professions VALUES (17,'Botanist',10,'Foraged items are always highest quality.',3,14);
INSERT INTO professions VALUES (18,'Tracker',10,'Location of forageable items revealed.',3,14);
INSERT INTO professions VALUES (19,'Fisher',5,'Fish worth 25% more.',4,null);
INSERT INTO professions VALUES (20,'Trapper',5,'Resources required to craft crab pots reduced.',4,null);
INSERT INTO professions VALUES (21,'Angler',10,'Fish worth 50% more.',4,19);
INSERT INTO professions VALUES (22,'Pirate',10,'Chance to find treasure doubled.',4,19);
INSERT INTO professions VALUES (23,'Mariner',10,'Crab pots no longer produce junk items.',4,20);
INSERT INTO professions VALUES (24,'Luremaster',10,'Crab pots no longer require bait.',4,20);
INSERT INTO professions VALUES (25,'Fighter',5,' All attacks deal 10% more damage.',5,null);
INSERT INTO professions VALUES (26,'Scout',5,'Critical strike chance increased by 50%.',5,null);
INSERT INTO professions VALUES (27,'Brute',10,'Deal 15% more damage.',5,25);
INSERT INTO professions VALUES (28,'Acrobat',10,'Cooldown on special moves cut in half.',5,25);
INSERT INTO professions VALUES (29,'Defender',10,'.',5,26);
INSERT INTO professions VALUES (30,'Desperado',10,'Critical strikes are deadlier.',5,26);

INSERT INTO villagers VALUES (1,'Alex',1,1,1,0);
INSERT INTO villagers VALUES (2,'Elliott',1,1,1,0);
INSERT INTO villagers VALUES (3,'Harvey',1,1,1,0);
INSERT INTO villagers VALUES (4,'Sam',1,1,1,0);
INSERT INTO villagers VALUES (5,'Sebastian',1,1,1,0);
INSERT INTO villagers VALUES (6,'Shane',1,1,1,0);
INSERT INTO villagers VALUES (7,'Abigail',1,1,0,1);
INSERT INTO villagers VALUES (8,'Emily',1,1,0,1);
INSERT INTO villagers VALUES (9,'Haley',1,1,0,1);
INSERT INTO villagers VALUES (10,'Leah',1,1,0,1);
INSERT INTO villagers VALUES (11,'Maru',1,1,0,1);
INSERT INTO villagers VALUES (12,'Penny',1,1,0,1);
INSERT INTO villagers VALUES (13,'Caroline',1,0,0,0);
INSERT INTO villagers VALUES (14,'Clint',1,0,0,0);
INSERT INTO villagers VALUES (15,'Demetrius',1,0,0,0);
INSERT INTO villagers VALUES (16,'Dwarf',1,0,0,0);
INSERT INTO villagers VALUES (17,'Evelyn',1,0,0,0);
INSERT INTO villagers VALUES (18,'George',1,0,0,0);
INSERT INTO villagers VALUES (19,'Gus',1,0,0,0);
INSERT INTO villagers VALUES (20,'Jas',1,0,0,0);
INSERT INTO villagers VALUES (21,'Jodi',1,0,0,0);
INSERT INTO villagers VALUES (22,'Kent',1,0,0,0);
INSERT INTO villagers VALUES (23,'Krobus',1,0,0,0);
INSERT INTO villagers VALUES (24,'Leo',1,0,0,0);
INSERT INTO villagers VALUES (25,'Lewis',1,0,0,0);
INSERT INTO villagers VALUES (26,'Linus',1,0,0,0);
INSERT INTO villagers VALUES (27,'Marnie',1,0,0,0);
INSERT INTO villagers VALUES (28,'Pam',1,0,0,0);
INSERT INTO villagers VALUES (29,'Pierre',1,0,0,0);
INSERT INTO villagers VALUES (30,'Robin',1,0,0,0);
INSERT INTO villagers VALUES (31,'Sandy',1,0,0,0);
INSERT INTO villagers VALUES (32,'Vincent',1,0,0,0);
INSERT INTO villagers VALUES (33,'Willy',1,0,0,0);
INSERT INTO villagers VALUES (34,'Wizard',1,0,0,0);
INSERT INTO villagers VALUES (35,'Birdie',0,0,0,0);
INSERT INTO villagers VALUES (36,'Bouncer',0,0,0,0);
INSERT INTO villagers VALUES (37,'Gil',0,0,0,0);
INSERT INTO villagers VALUES (38,'Governor',0,0,0,0);
INSERT INTO villagers VALUES (39,'Grandpa',0,0,0,0);
INSERT INTO villagers VALUES (40,'Gunther',0,0,0,0);
INSERT INTO villagers VALUES (41,'Henchman',0,0,0,0);
INSERT INTO villagers VALUES (42,'Marlon',0,0,0,0);
INSERT INTO villagers VALUES (43,'Morris',0,0,0,0);
INSERT INTO villagers VALUES (44,'Mr. Qi',0,0,0,0);
INSERT INTO villagers VALUES (45,'Professor Snail',0,0,0,0);